### ISSUE TITLE
Creación rápida de web

### ISSUE THREAD

**Issue by javacasm** [iblancasa/miercolesgeek#13]
Viendo el genial aspecto que habéis dado a la web http://hack-miniblip.github.io/ (y lo rápido que lo habéis montado) pensaba que quizás sería interesante explicar cómo hacerlo.

**Comment by iblancasa** [comment]
Bueno.. pero solo he cogido un template HTML y me he puesto a trabajar en ella...
[Aquí JJ pedía una web y yo proponía la plantilla y tal...](https://github.com/hack-miniblip/hack-miniblip.github.io/issues/59)

**Comment by iblancasa** [comment]
Cierro por que sería hablar solo de HTML y CSS

**Comment by angrykoala** [comment]
porque se a reabierto?

**Comment by iblancasa** [comment]
Lo haría sin querer
