### ISSUE TITLE
TORtilla con Cebolla (TOR and the Deepweb - A technical approach)

### ISSUE THREAD

**Issue by marco-fp** [iblancasa/miercolesgeek#16]
Propongo dar una Charla/Taller/Coloquio sobre el funcionamiento del protocolo TOR, el enrutamiento Onion y por qué la deep web no es helado oscuro.

Si os parece bien, asignad la fecha lo antes posible al volver de navidul.

**Comment by Nitrosito** [comment]
Lo secundo :penguin:

**Comment by iblancasa** [comment]
Sí, sería la primera semana después de Navidad por que tampoco hay mucho margen (o ya después de exámenes)

**Comment by JArandaIzquierdo** [comment]
Lo veo !

**Comment by Makova** [comment]
Yo también lo veo con un trío.

Manu

**Comment by marco-fp** [comment]
Genial entonces, a mi me da lo mismo antes de los exámenes que después. Si la primera semana al volver de navidad está libre pues esa misma.

**Comment by iblancasa** [comment]
Pues asígnate fecha :D

**Comment by iblancasa** [comment]
He estado hablando con @MarFerPra a raíz de una conversación que tuvimos ayer durante el Ubuntu&Beers algunos. Vamos a pasar la fecha a después de los exámenes para que la gente pueda ir.

Los exámenes acaban el 13 de febrero: ¿os parece el 17 (primer miércoles)?

**Comment by angrykoala** [comment]
Por mi vale

**Comment by ghost** [comment]
Perfecto!

**Comment by iblancasa** [comment]
Bueno, pues ya tenemos fecha y hora http://www.meetup.com/es-ES/Granada-Geek

**Comment by angrykoala** [comment]
Actualizar el readme!

**Comment by JJ** [comment]
Actualiza y cierra el issue, porfa.

**Comment by angrykoala** [comment]
Los issues no se cierra cuando se haga la charla?

**Comment by marco-fp** [comment]
Yo le he hecho caso a JJ, que no quiero que me coja manía para el año que viene. 
ele o ele

**Comment by JJ** [comment]
NO, cuando se pone la fecha...

El 10 de febrero de 2016, 13:23, lucyph3r notifications@github.com
escribió:

> Yo le he hecho caso a JJ, que no quiero que me coja manía para el año que
> viene.
> ele o ele
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/miercolesgeek/issues/16#issuecomment-182345557
> .

## 

JJ

**Comment by angrykoala** [comment]
Los ultimos estuvieron abiertos hasta la charla, pero bueno :confused:
