### ISSUE TITLE
Poner bonico el readme

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#2]
He hecho todo lo posible por hacer el readme chulo, pero las tablitas no me salen bien :cry: 

Poner mas chulo/mejor de alguna forma mágica

**Comment by iblancasa** [comment]
Voy a ver qué puedo hacer

**Comment by iblancasa** [comment]
O metemos HTML o no se puede hacer mucho más. Dejar los enlaces "al aire" como estaba, no me molaba. Así creo que mejor

**Comment by angrykoala** [comment]
demasiado acceder.. eso era lo que no me parece chulo...
quizas poner "Ver presentacion", "ver web" o linkear con el nombre directamente...

**Comment by iblancasa** [comment]
Espera, dame una miaja

**Comment by iblancasa** [comment]
¿Mejor? Yo creo que así está más recogido y todo. No sé

**Comment by angrykoala** [comment]
Esta chulo, solo que no se si la gente se enterará que hay que pinchar

**Comment by angrykoala** [comment]
tambien, la tabla (en raw) es feisima, quizas podriamos ponerlo como referencias. Por lo demás todo bien

**Comment by iblancasa** [comment]
No entiendo eso último... lo de en RAW :cry:

**Comment by angrykoala** [comment]
crudo, el texto readme, un markdown esta pensado para poderse leer sin interpretarlo no?

**Comment by iblancasa** [comment]
Sí.. bueno... pero en el momento que quieres meter una tabla o algo... es lo que hay

**Comment by angrykoala** [comment]
voy a probar el experimento a ver que te parece vale?

**Comment by angrykoala** [comment]
ale, ya esta, no se si ha quedado mejor o peor, a ver...

**Comment by iblancasa** [comment]
Ah bueno. Por mí vale

**Comment by angrykoala** [comment]
es un poco mas feo poner los links, pero al menos la tabla parece una tabla...
