### ISSUE TITLE
Android Invaders

### ISSUE THREAD

**Issue by ghost** [iblancasa/miercolesgeek#22]
Algunos alumnos del doble grado recién incorporados al grupo hemos pensado dar una charla sobre seguridad en dispositivos móviles, en este caso sobre seguridad en dispositivos con Android.

Hemos pensado que algunos de los puntos a tocar podrían ser los siguientes:
1. Introducción, algunos conceptos y explicación breve de las pruebas de concepto que se realizarán a lo largo de la charla.
2. Creación de un apk que permita la intrusión al sistema Android. Camuflando el apk creado con otra del market.
3. Prueba de concepto en red local. Intrusión en Android. ¿Cómo convertirse en root? 
4. Cómo trasladar eso a otras redes. Ataques fuera de LAN.

Si os parece bien el tema y quereis, podemos buscar una fecha y estaremos encantados de realizarla.

**Comment by angrykoala** [comment]
A mi me parece muy interesante, sobre fechas, diria que a principios de marzo (el miercoles 9 por ejemplo)

**Comment by ghost** [comment]
Esa fecha nos va bien a nosotros ;)

**Comment by angrykoala** [comment]
Ok, si os parece haced un pull request al readme con la información de la charla y links (tal y como estan las otras)

**Comment by iblancasa** [comment]
Hace falta que vayais diciendo hora @juanvelascogomez

**Comment by ghost** [comment]
Vale voy a hablarlo con el resto y os comentamos

**Comment by angrykoala** [comment]
Por cierto, alguna relación con #7 ? (si alguien sabe)

**Comment by ghost** [comment]
Nada, este es sobre seguridad en Android. Lo que viene siendo intrusión, vamos.

**Comment by angrykoala** [comment]
aah, vale vale :+1:
