### ISSUE TITLE
Taller de R

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#26]
R esta de moda, se de gente que no es de informatica que estan interesados.
Si alguien sabe algo de esto y tiene ganas

**Comment by JJ** [comment]
Yo puedo darlo, habrá que ver las fechas. ¿Hago un doodle o lo pongo un día por las buenas?

**Comment by angrykoala** [comment]
A mi me da igual, pero revisa todos los asuntos estos de congresos y cosas raras que la gente esta apuntándose a todo

**Comment by iblancasa** [comment]
Lo que veas J, echa un ojo al calendario para saber qué hay (más o menos) http://blog.iblancasa.com/calendario/

**Comment by JJ** [comment]
OK, miro y propongo una fecha.

**Comment by JJ** [comment]
El 23 de marzo parece el primer miércolesgeek libre.

**Comment by iblancasa** [comment]
Hacemos un doodle, ¿no?

**Comment by angrykoala** [comment]
La actualizo en el readme con los datos del meetup

**Comment by angrykoala** [comment]
No, ese es el de viasualizacion, cuando digais lo ponemos leñe

**Comment by JJ** [comment]
¿ein?

2016-03-09 20:03 GMT+01:00 Andrés notifications@github.com:

> No, ese es el de viasualizacion, cuando digais lo ponemos leñe
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/miercolesgeek/issues/26#issuecomment-194454533
> .

## 

JJ

**Comment by angrykoala** [comment]
Que esta el taller de visualizacion con R el dia 6 (que lo das tu no @JJ? pero que antes de eso conviene un taller de R a secas

**Comment by angrykoala** [comment]
el 23 es semana santa no? podriamos ponerla el 30

**Comment by JJ** [comment]
Como queráis.

2016-03-09 20:11 GMT+01:00 Andrés notifications@github.com:

> el 23 es semana santa no? podriamos ponerla el 30
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/miercolesgeek/issues/26#issuecomment-194457338
> .

## 

JJ

**Comment by angrykoala** [comment]
pues la pongo en el readme OK?

**Comment by JJ** [comment]
ok

2016-03-09 20:22 GMT+01:00 Andrés notifications@github.com:

> pues la pongo en el readme OK?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/miercolesgeek/issues/26#issuecomment-194463301
> .

## 

JJ

**Comment by JJ** [comment]
¿La has puesto en el README @demiurgosoft ? ¿Cuando?

**Comment by angrykoala** [comment]
erm, al final no se hizo ningun taller de R, solo el de visualizacion, que ya esta en el readme

**Comment by JJ** [comment]
Ya sé que no se hizo, lo que digo es si todavía interesa. Lo podría dar
Nuria, también.

**Comment by JJ** [comment]
Gente, tengo la reserva hecha para mañana. ¿La hacemos? ¿No la hacemos? ¿La cambiamos de día?

**Comment by iblancasa** [comment]
Para mañana va a ser demasiado precipitado

**Comment by JJ** [comment]
Yep, makes sense...

**Comment by angrykoala** [comment]
Perdon por no haber comentado @JJ @iblancasa , estoy cerrando issues que he creado hace mucho y no están activos Have a nice day!
