### ISSUE TITLE
Taller avanzado de javascript

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#28]
Alguien puede organizar un taller al estilo del del 8 de marzo, pero más avanzado?

**Comment by Nitrosito** [comment]
yo lo veo xD. A ver si @JJ convence al ponente de hoy para darlo jajaja. O alguien que se ofrezca. Pero el de hoy era mu apañao y gracioso xD

**Comment by JJ** [comment]
A ver si @vrivas se anima.

**Comment by vrivas** [comment]
Me alegro de que os gustara el taller de ayer.
Como os comenté, tengo algunas diapositivas sobre introducción a jQuery que podrían venir muy bien.
No obstante, los miércoles son días muy malos para mi, al menos hasta que acabemos las clases en Jaén (lo cual ocurrirá el 12 de mayo).

**Comment by angrykoala** [comment]
A ver, son los miercoles geek, pero que aqui las charlas se hacen cuando uno quiera, si estas dispuesto pues cuando mejor te vegan

PD: no se si la charla anterior entra en "miercoles geek" pero se podria poner como eventos pasados
