### ISSUE TITLE
Algo sobre Raspberry aprovechando la salida de Raspberry Pi Zero ?

### ISSUE THREAD

**Issue by JCristobal** [iblancasa/miercolesgeek#3]
[Raspberry Pi Zero, el nuevo y diminuto ordenador de solo 5 dólares](http://www.elconfidencial.com/tecnologia/2015-11-26/raspberry-pi-estrena-mini-ordenador-de-solo-5-dolares_1107538/)

Pues eso, ha salido por 5$ y aunque va justita pero se puede cacharrear con una por una miseria

Cuando haya algunas disponibles y alguien que entienda se podría pelear alguna charla/primer contacto/exposición de algo hecho ya (?)

:squirrel:

**Comment by iblancasa** [comment]
Podría estar bien una charla de iniciación a Raspberry:
- Cómo instalar un SO
- Primeros pasos
- Comparación entre los modelos
- Cómo funcionan los pines

**Comment by germaaan** [comment]
+1

**Comment by angrykoala** [comment]
Yo tengo dos raspberrys y algunas cositas hechas, no para dar toda la charla, pero para ayudar

**Comment by iblancasa** [comment]
Hombre... podemos hacer una cosa:
- Uno que cuente qué es Raspby y compare modelos y tal
- Otro que enseñe algo hecho

Una cosa que podría ser interesante a introducir en la charla sería añadir alternativas como Orange Pi y cosas así

**Comment by angrykoala** [comment]
de alternativas no se nada, yo entre mis proyectos (que podría mostrar mas o menos bien) tengo:
- Server estilo Dropbox (usando owncloud) y webserver típico
- Centro de videojuegos chulo (no recuerdo que era, pero una imagen estilo retropie)

Obviamente ver como configurar, conectar (temas de ssh,sftp,vnc...) y los programitas que vienen (minecraft,mathematica,scrath ...) habria que mirarlo

Por ultimo, alguna cosita conectando los pines gpio estaría chulo (de esto ya si que yo no se nada)

**Comment by javacasm** [comment]
Me ofrezco si queréis a dar una charla si no hay ponente. El material del último curso que monté sobre el tema está en https://github.com/javacasm/RaspberryPresencial

**Comment by angrykoala** [comment]
Por mi perfecto, cualquier miércoles que haya libre y te venga bien, si necesitas ayuda cuenta con mi hacha (tendremos que hablarlo con @JJ para reservar aula). Muchas gracias @javacasm !

**Comment by iblancasa** [comment]
Gracias :D @javacasm 
@JJ es quien nos lleva la reserva de aulas y cosas :D

**Comment by JJ** [comment]
El 16 está libre. Decidme hora y os reservo.

**Comment by angrykoala** [comment]
Si a @javacasm  le viene bien, lo normal es a las 10:30 o por la tarde (16:30/18:30) pero cómo el prefiera

**Comment by angrykoala** [comment]
(también puede ser un no miércoles por supuesto, no es como si el nombre del repositorio de a entender otra cosa)

**Comment by iblancasa** [comment]
Si puede ser por la mañana, mejor. Hemos detectado que hay algo más de afluencia de gente, pero sin problema :D

**Comment by javacasm** [comment]
Por mi perfecto el miércoles 16 a las 10:30. Por supuesto cuento con @demiurgosoft Nos dividimos la charla. ¿Creamos una carpeta en el repositorio para la charla (con nombre quizás ¿raspberry?) y añadimos un esquema de los contenidos?

**Comment by angrykoala** [comment]
Ok, tu haz el repo, ponme colaborador si quieres, yo te ayudo en lo que quieras (si quieres darlo todo tampoco hay problema), cuenta con que tengo una raspberry B+ y una raspberry 2 (ademas de algunos ethernet y un switch) tu organizas y yo ayudo en lo que necesites!

**Comment by javacasm** [comment]
Creado el repo https://github.com/javacasm/RaspberryMiercolesGeek y añadido @demiurgosoft 
He puesto un índice inicial. Si queréis podéis hacer vía issue los cambios que queráis

**Comment by angrykoala** [comment]
Yo comento los dos proyectos? Hay que ir con cuidado, porque habrá que comentar aspectos basicos (ssh, configuracion de ips... etc..)

**Comment by javacasm** [comment]
Por supuesto si quieres :)

**Comment by iblancasa** [comment]
@JJ @javacasm y @demiurgosoft ¿añado entonces al calendario?
@JCristobal -> ahí tienes tu charla

**Comment by JCristobal** [comment]
Perfecto! En una mañana menudo plan hemos apañado!

**Comment by angrykoala** [comment]
issues rock!

creo que podriamos dividir los proyectos, 1 tu y otro yo, si quieres comento de pasada el ssh y esas cosicas basicas, que yo no estoy tan puesto como tu en raspberrys

**Comment by javacasm** [comment]
Ok, por mi perfecto esa división. Y la charla ok en esa fecha

**Comment by angrykoala** [comment]
Ok, añado los datos en el README con una tablita en eventos proximos

**Comment by angrykoala** [comment]
ohm, y nombre? alguna idea? (temporalmente he puesto RaspberryGeek)

**Comment by iblancasa** [comment]
"Raspando la Pi". " Rasbperry pa ir tirando". Como sois dos: "Para ti la
Rasp y para mi la berry"

**Comment by JJ** [comment]
Jugo de frutas del bosque
Haciendo cosas en un raspispas
Raspiando que es gerundio

**Comment by iblancasa** [comment]
El gerundio está muy trillado

**Comment by angrykoala** [comment]
En serio? un grupo de informáticos y solo aparecéis para poner el nombre, que @javacasm decida

PD: no se como referenciar a otro comentario

**Comment by iblancasa** [comment]
@demiurgosoft ¡eeh! Que yo llevo apareciendo todo el rato. Cuando tengáis:
- Nombre
- Lugar
- Hora definitiva

Lo colocaré en el calendario y por el canal de Telegram

**Comment by angrykoala** [comment]
Dia 16, 10:30, usos multiples (nombre sera mas dificil XD)

Necesitaremos algun traductor hdmi-vga para conectar las raspberrys al proyector, yo tengo cables ethernet y un switch que valdran pa montar una mini-red

**Comment by JJ** [comment]
Creo que tenemos unos en la OSL.
