### ISSUE TITLE
Cambio de nombre -> Granada Geek

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/miercolesgeek#32]
Veréis:
la empresa esta que patrocina ha dicho que puede pagarnos un dominio y tal. Teniendo en cuenta que "Miércoles Geek" se hace los miércoles y no miércoles, que en Meetup "Granada Geek" está recogiendo tanto cosas de "Miércoles Geek" como de otras cosas... yo cambiaría el nombre a "Granada Geek".

Así:
- Nos unimos más con el Meetup
- Arreglo la web por si se deja de pagar el Meetup y no pierde "consistencia" (digo que al llamarse las dos cosas igual pues como que la transición de gente es menos problema)
- Abrimos a más días de los miércoles, aunque después se hacen cosas fuera de los miércoles

¿Qué os parece?

**Comment by Nitrosito** [comment]
Yo lo veo guay

**Comment by angrykoala** [comment]
a mí me mola más miercoles geek, pero vamos, que si tiene sentido unirlo, asi que como veais

**Comment by angrykoala** [comment]
PD: que cosas faltan por añadir a este repo? poned un issue o algo asi con lo que falta y ya lo pongo yo bonico si eso

**Comment by Nitrosito** [comment]
Esq como se llame miercoles geek y en el dominio granadageek.es va a ser un
poco lioso xD

**Comment by germaaan** [comment]
Mejor usar el mismo nombre en todos sitios, ya que además al fin y al cabo siempre somos los mismos en ambas cosas, xD
