### ISSUE TITLE
Web con la información de proyectos y links

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#4]
hacer una gh-pages con link a los proyectos (y al calendario) estaría bien

**Comment by iblancasa** [comment]
Cogemos alguna plantilla de por ahí (libre) y la tuneamos, ¿no?

**Comment by angrykoala** [comment]
Es la idea!, bastaria con poner algo parecido al readme creo yo, estoy liado esta mañana, pero si tu no puedes lo monto yo esta tarde

**Comment by iblancasa** [comment]
Vamos a proponer plantillas por aquí y vemos que usar (las que vienen por defecto no me gustan)

**Comment by angrykoala** [comment]
Uy, yo no se nada de meter plantillas que no sean por defecto :laughing:

**Comment by iblancasa** [comment]
Tu busca plantillas HTML 5 libres que te molen y las pegas aquí (las URL) y lo vamos viendo. Yo si lo uso mucho. Don't worry

**Comment by angrykoala** [comment]
:weary: Nunca me salvare del maldito front-end

**Comment by iblancasa** [comment]
A ver qué tal alguno de estos:
http://demo.themeisle.com/parallax-one/
http://html5up.net/solid-state
https://w3layouts.com/preview/?l=/we-photography-a-photographer-portfolio-flat-bootstrap-responsive-web-template/
http://webthemez.com/preview/?free-education-html5-template-ilearn/
http://azmind.com/demo/lancar/v1-0/

No sé, algo sencillito y limpio.

**Comment by angrykoala** [comment]
mmm, cualquiera vale, aunque algunas estan un pelin sobrecargadas (supongo que dependerá de lo que metamos), me quedaría con http://azmind.com/demo/lancar/v1-0/, http://html5up.net/solid-state o http://webthemez.com/preview/?free-education-html5-template-ilearn/ si cambiamos el color rojo

**Comment by Nitrosito** [comment]
Yo voto por lancar, pero its free?

**Comment by iblancasa** [comment]
Echa un ojo aquí Carlos
http://azmind.com/2015/01/10/lancar-bootstrap-one-page-agency-portfolio-free-template/

**Comment by angrykoala** [comment]
Pues parece que lancar es la favorita.... tu decides @iblancasa

**Comment by iblancasa** [comment]
No sé bajarla... si alguno sabe... o elegimos otra :S

**Comment by iblancasa** [comment]
Eliminando los motivos "verdes", este me gusta bastante
http://www.365bootstrap.com/demo/?cat=365bootstrap&temp=Chameleon

**Comment by angrykoala** [comment]
mmm, por mi vale

**Comment by Nitrosito** [comment]
@iblancasa para bajarla hay que registrarse y ale, a volar xD.
Pues nose, la utlima también tiene buena pinta, lo que querais.
Quizas a la ultima haya que cambiarle varias cosas. pero las 2 molan eh

**Comment by iblancasa** [comment]
¿Te la has conseguido bajar? Por que me registré, me enviaron el enlace y
ya no he podido hacer más nada... Sin volar

**Comment by iblancasa** [comment]
Me la he bajado de otro lado. Cuando tenga un rato, me pongo

**Comment by angrykoala** [comment]
OK :+1:

**Comment by iblancasa** [comment]
Tenemos esto... http://www.meetup.com/es-ES/Granada-Geek

¿Terminamos la web o no?

**Comment by angrykoala** [comment]
Erm, pero granada geek != miercoles geek no?

**Comment by iblancasa** [comment]
Ya... pero al final vamos los mismos a todo xD

**Comment by angrykoala** [comment]
I hate meetup, pero como veas, mientras sigas actualizando el calendario me vale

**Comment by iblancasa** [comment]
:+1:
