### ISSUE TITLE
¿Algún interesado en Unity (3D)?

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#6]
Unity 3D, como plataforma de desarrollo para videojuegos podría ser una herramienta interesante para una charla básica,media o avanzada (dependiendo del interés general)

> Sadly, not open-source :cry:

**Comment by Nitrosito** [comment]
Yop!
Pero los diseños 3D se hacen con unity o blender? (De blender también seria interesante)

**Comment by JArandaIzquierdo** [comment]
A mi me malaria también!

**Comment by angrykoala** [comment]
Unity es basura para hacer modelado, aunque otros motores como Unreal son mejores, lo normal es hacer los modelos en una herramienta específica (como blender, taller que molaría) y luego importarlos en el motor de juego

**Comment by iblancasa** [comment]
@demiurgosoft dijo ayer que podría dar algo
¿en torno al 2 de marzo? ;)

**Comment by angrykoala** [comment]
bufff, ni idea el 2 de marzo que sera de mi vida, pero en principio si queréis si, cuando sea la doy

**Comment by iblancasa** [comment]
Es por ir cubriendo... cuando se acerque más la fecha, se fija pero para tener una idea :D

**Comment by angrykoala** [comment]
okok, apúntala si quieres, la hora ya confirmaremos :+1:

**Comment by angrykoala** [comment]
vale, la hora creo que me vendria bien por la tarde (ya hora me da igual)

**Comment by iblancasa** [comment]
@demiurgosoft elige tú

**Comment by angrykoala** [comment]
yo que se, cuando a la gente no le de pereza venir, 16:30 o 17:30

**Comment by iblancasa** [comment]
@demiurgosoft esta charla es para el 2 de marzo. Seguimos sin hora

**Comment by iblancasa** [comment]
Perdón por cerrar

**Comment by JJ** [comment]
¿Se ha cambiado de día? ¿Reservo aula?

**Comment by angrykoala** [comment]
pero cuando se ha cambiado el dia? no es el 2 a las 19:30?

**Comment by JJ** [comment]
Ese es el de unity

El 15 de febrero de 2016, 10:14, Andrés notifications@github.com escribió:

> pero cuando se ha cambiado el dia? no es el 2 a las 19:30?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/miercolesgeek/issues/6#issuecomment-184126927
> .

## 

JJ

**Comment by angrykoala** [comment]
Pues eso, el 2 el de unity... no se ha cancelado
