### ISSUE TITLE
Taller de Blender

### ISSUE THREAD

**Issue by angrykoala** [iblancasa/miercolesgeek#8]
pues eso, como lo dicho en #6 un taller de modelado/animacion 3D en Blender molaría, si alguien sabe que lo diga

![](https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png)
_Blender rodriguez?_

**Comment by angrykoala** [comment]
Blender se puede usar también para impresión 3D ¿no?

**Comment by Nitrosito** [comment]
@demiurgosoft sip, por eso me interesa más aún jaja.
Pues yo tengo un colega que hizo el curso este de 1 año con arkam studios de videojuegos. Sabe de blender y unity, lo mismo nos podria explicar algo jaja

**Comment by angrykoala** [comment]
de unity yo algo controlo, pero de blender ni idea, coméntaselo a ver que nos dice

**Comment by angrykoala** [comment]
El padre de la novia de un amigo a lo mejor se anima a dar alguna cosilla de blender, es de una empresa de animación de aquí de granada, ya os informare de como va

**Comment by iblancasa** [comment]
@demiurgosoft :O

**Comment by Nitrosito** [comment]
@demiurgosoft queremos información xDDD
¿Es de Mundrop?

**Comment by angrykoala** [comment]
Ni idea, no me han proporcionado mas información. Seguiremos informando

**Comment by JJ** [comment]
@demiurgosoft ¿le has preguntado?

**Comment by angrykoala** [comment]
han desaparecido, necesitamos otra gente que sepa de blender
