### ISSUE TITLE
¿Alguien se anima a contar Docker?

### ISSUE THREAD

**Issue by JJ** [iblancasa/miercolesgeek#9]
Es una tecnología muy interesante y útil para todo tipo de cosas...

**Comment by angrykoala** [comment]
sería interesante, no se apenas nada de docker salvo que el logo es una ballena muy cuca

**Comment by iblancasa** [comment]
@JJ más que tú, de los que hay por aquí al menos, no sabe nadie. Podrías contar también lo que te contó el señor ese de Microsoft que habían virtualizado Windows con eso ¿era con eso?

**Comment by JJ** [comment]
Sí... Pero no quiero a) aburriros dándolo todo yo y b) prepararme tantas
cosas, que acabo molío... ¿No se anima nadie?

**Comment by angrykoala** [comment]
Yo lo haría pero ni idea de docker... @iblancasa no sabe de eso?

**Comment by iblancasa** [comment]
Un poco :+1:

**Comment by angrykoala** [comment]
pues te toca :laughing:

**Comment by iblancasa** [comment]
@JJ había comentado de hablar con alguien para que diese una charla sobre Docker. Coméntale a ver qué le parecería en torno al 24 de febrero :dancer:

**Comment by JJ** [comment]
@hugobarzano sabe un montón sobre el tema. Si se anima...

**Comment by hugobarzano** [comment]
Perooo charla en plan como?

**Comment by JJ** [comment]
En plan guay.

**Comment by iblancasa** [comment]
@JJ "en plan guay" JAJAJAJAJA

**Comment by hugobarzano** [comment]
Tampoco es que maneje mucho del tema, pero dejadme que lo piense...

**Comment by JJ** [comment]
¡Gracias!

**Comment by JJ** [comment]
Al final se presentó al principio del hackatón, así que cierro.
